# Generated by Django 6.0.5 on 2026-08-04 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('pprice', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
    ]
